### ISSUE TITLE
Create gulp plugin

### ISSUE THREAD

**Issue by lolbeans** [killercup/grock#15]
Hi, what would be involved in creating a gulp plugin for this? I'm not sure how to go about it?

Thanks

**Comment by legomushroom** [comment]
Hi, good time of the day!

Thanks for the `grock` :heart:! I would love to see the gulp plugin too, is there any update for the topic?
Currently I'm trying to use the approach from the second comment but no luck:

`Error: Cannot find module '../styles/undefined'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.module.exports [as generator] (/Applications/MAMP/htdocs/mojs/node_modules/grock/lib/generator.coffee:38:11)
  at Gulp.gulp.task.gulp.src.pipe.plumber.errorHandler (/Applications/MAMP/htdocs/mojs/gulpfile.js:103:16)
  at module.exports (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at Gulp.<anonymous> (/Applications/MAMP/htdocs/mojs/node_modules/gulp/index.js:36:18)
  at Gaze.<anonymous> (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
  at Gaze.emit (events.js:98:17)
  at Gaze.emit (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
  at /Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:415:16
  at StatWatcher._pollers.(anonymous function) (/Applications/MAMP/htdocs/mojs/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:326:7)
  at StatWatcher.emit (events.js:98:17)
  at StatWatcher._handle.onchange (fs.js:1115:10)`

Thanks for your help!

**Comment by killercup** [comment]
Hi, @legomushroom!

The error `Cannot find module '../styles/undefined'` sounds like there is something wrong with the style you specified – or the lack of thereof. It's nothing specific to gulp, by the way (as there it's literally just calling the main _grock_ generator).

Try setting `style: "thin"` when calling `grock.generator`.

PS: I'm not sure right now, but could it be that `grock.generator` doesn't set any default values?
**Edit:** Yes, indeed. There are no defaults for [the options](https://github.com/killercup/grock/blob/4c7f63a010952bb4292b791b86e48c7871b2efa7/lib/generator.coffee#L30).

**Comment by killercup** [comment]
> I would love to see the gulp plugin too, is there any update for the topic?

There is no update on a special gulp plugin as there is none and there should not be one. (See my comments above.)

If there is any interest in making _grock_ more integrated with _gulp_, I'd be happy to see a pull request that refactors _grock's_ generator interface to read _vinyl_ streams and returns a stream with the _vinyl_ objects _grock_ creates anyway.

**Comment by legomushroom** [comment]
Thanks for your fast response!

Yep, specifying the `style` field works.
Seems like your are right - there is no `defaults` in generator.
What are the options for the `style` field can't find anywhere?

**Thanks a lot!**

**Comment by killercup** [comment]
@legomushroom glad it worked. Valid style options are the subdirectories of `styles/`, i.e. "solarized" and "thin", currently.
